export const SERIES_TYPES = [
  "cash_bill",
  "credit_bill",
  "draft_cash_bill",
  "draft_credit_bill",
  "stock_inward",
  "credit_note",
  "stock_damage",
  "stock_block",
  "stock_transfer",
  "positive_adjustment",
  "negative_adjustment",
  "opening_balance",
  "entry_correction",
  "payment_request",
  "refund",
  "bill_cancellation",
  "bill_return",
  "bill_payment",
  "shift",
  "online_bill",
  "quality_check",
  "product_request",
] as const;

export const SERIES_PREFIXES: Record<(typeof SERIES_TYPES)[number], string> = {
  cash_bill: "CB",
  credit_bill: "CR",
  draft_cash_bill: "DRFTCB",
  draft_credit_bill: "DRFTCR",
  stock_inward: "SI",
  credit_note: "CN",
  stock_damage: "SD",
  stock_block: "SB",
  stock_transfer: "ST",
  positive_adjustment: "PA",
  negative_adjustment: "NA",
  opening_balance: "OB",
  entry_correction: "EC",
  payment_request: "PR",
  refund: "RF",
  bill_cancellation: "BX",
  bill_return: "BR",
  bill_payment: "BP",
  shift: "SH",
  online_bill: "OB2",
  quality_check: "QC",
  product_request: "PQ",
};
