import type {
  BillTemplateData,
  CreditNoteTemplateData,
  RefundTemplateData,
} from "@/lib/billing/renderBillTemplate";

export const SAMPLE_BILL_DATA: BillTemplateData = {
  documentNumber: "CB/2027-28/0001",
  billType: "cash_bill",
  billDate: "01/09/2026",
  status: "completed",
  storeName: "Sample Store",
  storeAddress: "123 Sample Street, Sample City",
  storeGstin: "22AAAAA0000A1Z5",
  storeStateName: "Delhi",
  storeStateCode: "DL",
  storeLogoUrl: null,
  headerText: "Thank you for shopping with us",
  footerText: "Goods once sold will not be taken back",
  returnPolicyText: "Returns accepted within 7 days with the receipt",
  customerName: "Jane Doe",
  customerPhone: "9876543210",
  customerAddress: "45 Customer Lane, Sample City",
  customerGstin: "22BBBBB1111B1Z6",
  cashierName: "Alex Cashier",
  terminalName: "Counter 1",
  lines: [
    {
      productName: "Sample Product A",
      productBarcode: "1000000000001",
      productHsnCode: "1006",
      quantity: 2,
      unitPrice: 150,
      discountApplied: 0,
      lineAmount: 300,
      lineTotal: 300,
    },
    {
      productName: "Sample Product B",
      productBarcode: "1000000000002",
      productHsnCode: "2106",
      quantity: 1,
      unitPrice: 250,
      discountApplied: 10,
      lineAmount: 240,
      lineTotal: 268,
    },
  ],
  subtotal: 550,
  discountTotal: 10,
  netSubtotal: 540,
  cgstAmount: 14,
  sgstAmount: 14,
  igstAmount: 0,
  taxTotal: 28,
  grandTotal: 568,
};

export const SAMPLE_CREDIT_NOTE_DATA: CreditNoteTemplateData = {
  documentNumber: "CN/2027-28/0001",
  createdAt: "01/09/2026",
  storeName: "Sample Store",
  storeAddress: "123 Sample Street, Sample City",
  storeGstin: "22AAAAA0000A1Z5",
  storeLogoUrl: null,
  customerName: "Jane Doe",
  customerPhone: "9876543210",
  originalBillDocumentNumber: "CB/2027-28/0001",
  reasonLabel: "Customer changed mind",
  amount: 161.78,
  taxBreakdown: { cgstAmount: 4, sgstAmount: 4, igstAmount: 0, taxAmount: 8 },
};

export const SAMPLE_REFUND_DATA: RefundTemplateData = {
  documentNumber: "RF/2027-28/0001",
  createdAt: "01/09/2026",
  storeName: "Sample Store",
  storeAddress: "123 Sample Street, Sample City",
  storeGstin: "22AAAAA0000A1Z5",
  storeLogoUrl: null,
  originalBillDocumentNumber: "CB/2027-28/0001",
  sourceType: "Return",
  sourceDocumentNumber: "BR/2027-28/0001",
  refundMethodName: "Cash",
  status: "completed",
  amount: 161.78,
};
